version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: goals-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: goals
      MYSQL_USER: g_user
      MYSQL_PASSWORD: TestPass123!
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
